from src.card import MonsterCard, Element, Rarity

ALL_CARDS_DB = {
    1: MonsterCard(1, "Spore-Seed", "Uma criatura misteriosa.", Rarity.ULTRA_RARE, Element.NORMAL, 7, 3500, 2800, "assets/images/cropped_cards/card_1.png"),
    2: MonsterCard(2, "Moss-Lizard", "Uma criatura misteriosa.", Rarity.EPIC, Element.NORMAL, 7, 2400, 2200, "assets/images/cropped_cards/card_2.png"),
    3: MonsterCard(3, "Verdant-Dragon", "Uma criatura misteriosa.", Rarity.UNCOMMON, Element.NORMAL, 4, 1800, 1400, "assets/images/cropped_cards/card_3.png"),
    4: MonsterCard(4, "Ember-Chick", "Uma criatura misteriosa.", Rarity.ULTRA_RARE, Element.NORMAL, 7, 2800, 2300, "assets/images/cropped_cards/card_4.png"),
    5: MonsterCard(5, "Magma-Boar", "Uma criatura misteriosa.", Rarity.UNCOMMON, Element.NORMAL, 4, 1600, 1200, "assets/images/cropped_cards/card_5.png"),
    6: MonsterCard(6, "Flare-Steed", "Uma criatura misteriosa.", Rarity.RARE, Element.NORMAL, 6, 1500, 1200, "assets/images/cropped_cards/card_6.png"),
    7: MonsterCard(7, "Droplet-Frog", "Uma criatura misteriosa.", Rarity.ULTRA_RARE, Element.NORMAL, 8, 3000, 2400, "assets/images/cropped_cards/card_7.png"),
    8: MonsterCard(8, "Tide-Whale", "Uma criatura misteriosa.", Rarity.RARE, Element.NORMAL, 6, 2300, 2000, "assets/images/cropped_cards/card_8.png"),
    9: MonsterCard(9, "Spark-Cat", "Uma criatura misteriosa.", Rarity.RARE, Element.NORMAL, 4, 2100, 1400, "assets/images/cropped_cards/card_9.png"),
    10: MonsterCard(10, "Thunder-Lynx", "Uma criatura misteriosa.", Rarity.COMMON, Element.NORMAL, 3, 1000, 400, "assets/images/cropped_cards/card_10.png"),
    11: MonsterCard(11, "Volt-Lion", "Uma criatura misteriosa.", Rarity.COMMON, Element.NORMAL, 4, 1100, 500, "assets/images/cropped_cards/card_11.png"),
    12: MonsterCard(12, "Sand-Scorpion", "Uma criatura misteriosa.", Rarity.ULTRA_RARE, Element.FIRE, 7, 2600, 2400, "assets/images/cropped_cards/card_12.png"),
    13: MonsterCard(13, "Desert-Wyrm", "Uma criatura misteriosa.", Rarity.EPIC, Element.NORMAL, 6, 2500, 2000, "assets/images/cropped_cards/card_13.png"),
    14: MonsterCard(14, "Dune-Dervish", "Uma criatura misteriosa.", Rarity.RARE, Element.NORMAL, 4, 2400, 1600, "assets/images/cropped_cards/card_14.png"),
    15: MonsterCard(15, "Ice-Cub", "Uma criatura misteriosa.", Rarity.COMMON, Element.NORMAL, 4, 800, 1100, "assets/images/cropped_cards/card_15.png"),
    16: MonsterCard(16, "Frost-Wolf", "Uma criatura misteriosa.", Rarity.ULTRA_RARE, Element.NORMAL, 6, 3500, 2100, "assets/images/cropped_cards/card_16.png"),
    17: MonsterCard(17, "Glacier-Bear", "Uma criatura misteriosa.", Rarity.COMMON, Element.NORMAL, 4, 1200, 1300, "assets/images/cropped_cards/card_17.png"),
    18: MonsterCard(18, "Toxic-Slime", "Uma criatura misteriosa.", Rarity.UNCOMMON, Element.NORMAL, 5, 1500, 1600, "assets/images/cropped_cards/card_18.png"),
    19: MonsterCard(19, "Venom-Gator", "Uma criatura misteriosa.", Rarity.COMMON, Element.FIRE, 4, 700, 500, "assets/images/cropped_cards/card_19.png"),
    20: MonsterCard(20, "Vile-Stalker", "Uma criatura misteriosa.", Rarity.EPIC, Element.FIRE, 5, 2900, 1600, "assets/images/cropped_cards/card_20.png"),
    21: MonsterCard(21, "Iron-Beetle", "Uma criatura misteriosa.", Rarity.RARE, Element.FIRE, 6, 2500, 2100, "assets/images/cropped_cards/card_21.png"),
    22: MonsterCard(22, "Steel-Sentry", "Uma criatura misteriosa.", Rarity.UNCOMMON, Element.NORMAL, 3, 1100, 900, "assets/images/cropped_cards/card_22.png"),
    23: MonsterCard(23, "Steel-Sentry (Dup)", "Uma criatura misteriosa.", Rarity.EPIC, Element.NORMAL, 7, 3000, 2500, "assets/images/cropped_cards/card_23.png"),
    24: MonsterCard(24, "Rock-Lobster", "Uma criatura misteriosa.", Rarity.UNCOMMON, Element.NORMAL, 3, 1700, 800, "assets/images/cropped_cards/card_24.png"),
    25: MonsterCard(25, "Cave-Bat", "Uma criatura misteriosa.", Rarity.ULTRA_RARE, Element.NORMAL, 6, 2500, 2400, "assets/images/cropped_cards/card_25.png"),
    26: MonsterCard(26, "Cavern-Creeper", "Uma criatura misteriosa.", Rarity.EPIC, Element.NORMAL, 7, 3000, 1600, "assets/images/cropped_cards/card_26.png"),
    27: MonsterCard(27, "Geo-Gargoyle", "Uma criatura misteriosa.", Rarity.RARE, Element.FIRE, 4, 2400, 1800, "assets/images/cropped_cards/card_27.png"),
    28: MonsterCard(28, "Fairy-Pixie", "Uma criatura misteriosa.", Rarity.ULTRA_RARE, Element.FIRE, 7, 3200, 2100, "assets/images/cropped_cards/card_28.png"),
    29: MonsterCard(29, "Fae-Dragonfly", "Uma criatura misteriosa.", Rarity.ULTRA_RARE, Element.FIRE, 6, 2500, 2900, "assets/images/cropped_cards/card_29.png"),
    30: MonsterCard(30, "Mystic-Unicorn", "Uma criatura misteriosa.", Rarity.RARE, Element.NORMAL, 4, 1800, 2000, "assets/images/cropped_cards/card_30.png"),
    31: MonsterCard(31, "Spook-Specter", "Uma criatura misteriosa.", Rarity.RARE, Element.NORMAL, 6, 2200, 1700, "assets/images/cropped_cards/card_31.png"),
    32: MonsterCard(32, "Ghost-Owl", "Uma criatura misteriosa.", Rarity.UNCOMMON, Element.NORMAL, 3, 1300, 1400, "assets/images/cropped_cards/card_32.png"),
    33: MonsterCard(33, "Phantom-Rider", "Uma criatura misteriosa.", Rarity.EPIC, Element.NORMAL, 5, 2900, 2400, "assets/images/cropped_cards/card_33.png"),
    34: MonsterCard(34, "Void-Seed", "Uma criatura misteriosa.", Rarity.RARE, Element.NORMAL, 6, 1500, 2000, "assets/images/cropped_cards/card_34.png"),
    35: MonsterCard(35, "Chaos-Crawler", "Uma criatura misteriosa.", Rarity.COMMON, Element.FIRE, 3, 1300, 1400, "assets/images/cropped_cards/card_35.png"),
    36: MonsterCard(36, "Abyss-Watcher", "Uma criatura misteriosa.", Rarity.RARE, Element.FIRE, 4, 1600, 2000, "assets/images/cropped_cards/card_36.png"),
    37: MonsterCard(37, "Steam-Punk Rat", "Uma criatura misteriosa.", Rarity.COMMON, Element.FIRE, 4, 900, 1400, "assets/images/cropped_cards/card_37.png"),
    38: MonsterCard(38, "Gear-Golem", "Uma criatura misteriosa.", Rarity.ULTRA_RARE, Element.NORMAL, 6, 3300, 2000, "assets/images/cropped_cards/card_38.png"),
    39: MonsterCard(39, "Clockwork Phoenix", "Uma criatura misteriosa.", Rarity.UNCOMMON, Element.NORMAL, 4, 1400, 800, "assets/images/cropped_cards/card_39.png"),
    40: MonsterCard(40, "Root-Sentinel", "Uma criatura misteriosa.", Rarity.ULTRA_RARE, Element.NORMAL, 6, 2600, 2200, "assets/images/cropped_cards/card_40.png"),
    41: MonsterCard(41, "Ancient-Turtle", "Uma criatura misteriosa.", Rarity.COMMON, Element.NORMAL, 2, 1000, 1400, "assets/images/cropped_cards/card_41.png"),
    42: MonsterCard(42, "Forest-Spirit", "Uma criatura misteriosa.", Rarity.ULTRA_RARE, Element.NORMAL, 7, 3400, 3000, "assets/images/cropped_cards/card_42.png"),
    43: MonsterCard(43, "Solar-Sprite", "Uma criatura misteriosa.", Rarity.RARE, Element.NORMAL, 4, 2100, 1600, "assets/images/cropped_cards/card_43.png"),
    44: MonsterCard(44, "Lunar-Serpent", "Uma criatura misteriosa.", Rarity.EPIC, Element.NORMAL, 6, 3000, 2100, "assets/images/cropped_cards/card_44.png"),
    45: MonsterCard(45, "Nebula-Whale", "Uma criatura misteriosa.", Rarity.EPIC, Element.NORMAL, 7, 3000, 2500, "assets/images/cropped_cards/card_45.png"),
    46: MonsterCard(46, "Comet-Fox", "Uma criatura misteriosa.", Rarity.UNCOMMON, Element.NORMAL, 4, 1800, 800, "assets/images/cropped_cards/card_46.png"),
    47: MonsterCard(47, "Gravity-Manta", "Uma criatura misteriosa.", Rarity.COMMON, Element.NORMAL, 2, 1300, 1400, "assets/images/cropped_cards/card_47.png"),
    48: MonsterCard(48, "Quantum-Cube", "Uma criatura misteriosa.", Rarity.COMMON, Element.NORMAL, 4, 1000, 1200, "assets/images/cropped_cards/card_48.png"),
    49: MonsterCard(49, "Ptorcaget", "Uma criatura misteriosa.", Rarity.UNCOMMON, Element.NORMAL, 5, 1200, 1100, "assets/images/cropped_cards/card_49.png"),
    50: MonsterCard(50, "Forctoqak", "Uma criatura misteriosa.", Rarity.COMMON, Element.NORMAL, 4, 600, 1300, "assets/images/cropped_cards/card_50.png"),
    51: MonsterCard(51, "Freleaf", "Uma criatura misteriosa.", Rarity.UNCOMMON, Element.NORMAL, 4, 1300, 800, "assets/images/cropped_cards/card_51.png"),
    52: MonsterCard(52, "Freleaf (Dup)", "Uma criatura misteriosa.", Rarity.ULTRA_RARE, Element.NORMAL, 8, 3100, 2900, "assets/images/cropped_cards/card_52.png"),
    53: MonsterCard(53, "Seedling", "Uma criatura misteriosa.", Rarity.ULTRA_RARE, Element.NORMAL, 7, 2500, 2600, "assets/images/cropped_cards/card_53.png"),
    54: MonsterCard(54, "Bloomleaf", "Uma criatura misteriosa.", Rarity.UNCOMMON, Element.NORMAL, 4, 1400, 900, "assets/images/cropped_cards/card_54.png"),
    55: MonsterCard(55, "Chrysalid", "Uma criatura misteriosa.", Rarity.EPIC, Element.NORMAL, 6, 2500, 2600, "assets/images/cropped_cards/card_55.png"),
    56: MonsterCard(56, "Armored-Moth", "Uma criatura misteriosa.", Rarity.EPIC, Element.NORMAL, 5, 2600, 2100, "assets/images/cropped_cards/card_56.png"),
    57: MonsterCard(57, "Leafdit", "Uma criatura misteriosa.", Rarity.RARE, Element.NORMAL, 5, 1800, 1300, "assets/images/cropped_cards/card_57.png"),
    58: MonsterCard(58, "Bloomnig", "Uma criatura misteriosa.", Rarity.EPIC, Element.NORMAL, 5, 2500, 1700, "assets/images/cropped_cards/card_58.png"),
    59: MonsterCard(59, "Mossjhn", "Uma criatura misteriosa.", Rarity.ULTRA_RARE, Element.NORMAL, 7, 2500, 2500, "assets/images/cropped_cards/card_59.png"),
    60: MonsterCard(60, "Moomango", "Uma criatura misteriosa.", Rarity.ULTRA_RARE, Element.NORMAL, 7, 3000, 2400, "assets/images/cropped_cards/card_60.png"),
    61: MonsterCard(61, "Emdeocot", "Uma criatura misteriosa.", Rarity.ULTRA_RARE, Element.NORMAL, 6, 2800, 2100, "assets/images/cropped_cards/card_61.png"),
    62: MonsterCard(62, "Hatchling", "Uma criatura misteriosa.", Rarity.ULTRA_RARE, Element.NORMAL, 7, 2500, 2900, "assets/images/cropped_cards/card_62.png"),
    63: MonsterCard(63, "Myvern", "Uma criatura misteriosa.", Rarity.COMMON, Element.NORMAL, 2, 1000, 1200, "assets/images/cropped_cards/card_63.png"),
    64: MonsterCard(64, "Ancient-Dragon", "Uma criatura misteriosa.", Rarity.ULTRA_RARE, Element.NORMAL, 6, 3500, 2700, "assets/images/cropped_cards/card_64.png"),
    65: MonsterCard(65, "Deepdiver", "Uma criatura misteriosa.", Rarity.ULTRA_RARE, Element.NORMAL, 6, 3500, 2600, "assets/images/cropped_cards/card_65.png"),
    66: MonsterCard(66, "Shacdart", "Uma criatura misteriosa.", Rarity.RARE, Element.FIRE, 4, 2400, 2000, "assets/images/cropped_cards/card_66.png"),
    67: MonsterCard(67, "Volt-Vulture", "Uma criatura misteriosa.", Rarity.COMMON, Element.FIRE, 2, 500, 400, "assets/images/cropped_cards/card_67.png"),
    68: MonsterCard(68, "Spark-Smail", "Uma criatura misteriosa.", Rarity.RARE, Element.FIRE, 6, 1700, 1700, "assets/images/cropped_cards/card_68.png"),
    69: MonsterCard(69, "Iron-Impant", "Uma criatura misteriosa.", Rarity.UNCOMMON, Element.FIRE, 3, 1100, 1300, "assets/images/cropped_cards/card_69.png"),
    70: MonsterCard(70, "Static-Spark", "Uma criatura misteriosa.", Rarity.UNCOMMON, Element.NORMAL, 4, 1600, 1400, "assets/images/cropped_cards/card_70.png"),
    71: MonsterCard(71, "Volt-Gurkinim", "Uma criatura misteriosa.", Rarity.ULTRA_RARE, Element.NORMAL, 8, 3500, 2300, "assets/images/cropped_cards/card_71.png"),
    72: MonsterCard(72, "Mecha-Generator", "Uma criatura misteriosa.", Rarity.UNCOMMON, Element.FIRE, 4, 1400, 1500, "assets/images/cropped_cards/card_72.png"),
    73: MonsterCard(73, "Rohmles-Keetle", "Uma criatura misteriosa.", Rarity.UNCOMMON, Element.NORMAL, 5, 1100, 800, "assets/images/cropped_cards/card_73.png"),
    74: MonsterCard(74, "Muscle-Mole", "Uma criatura misteriosa.", Rarity.ULTRA_RARE, Element.FIRE, 8, 2700, 2700, "assets/images/cropped_cards/card_74.png"),
    75: MonsterCard(75, "Muscle-Mole (Dup)", "Uma criatura misteriosa.", Rarity.EPIC, Element.FIRE, 6, 2200, 1800, "assets/images/cropped_cards/card_75.png"),
    76: MonsterCard(76, "Punch-Penguin", "Uma criatura misteriosa.", Rarity.EPIC, Element.FIRE, 5, 2700, 2500, "assets/images/cropped_cards/card_76.png"),
    77: MonsterCard(77, "Dust-Revil", "Uma criatura misteriosa.", Rarity.ULTRA_RARE, Element.FIRE, 8, 2500, 3000, "assets/images/cropped_cards/card_77.png"),
    78: MonsterCard(78, "Sprad-Mecl", "Uma criatura misteriosa.", Rarity.UNCOMMON, Element.NORMAL, 4, 1300, 1500, "assets/images/cropped_cards/card_78.png"),
    79: MonsterCard(79, "Mhu-Mibst", "Uma criatura misteriosa.", Rarity.COMMON, Element.NORMAL, 3, 1200, 700, "assets/images/cropped_cards/card_79.png"),
    80: MonsterCard(80, "Roes-Heck", "Uma criatura misteriosa.", Rarity.COMMON, Element.FIRE, 2, 1200, 1100, "assets/images/cropped_cards/card_80.png"),
    81: MonsterCard(81, "Frost-Foy", "Uma criatura misteriosa.", Rarity.UNCOMMON, Element.NORMAL, 3, 1200, 1200, "assets/images/cropped_cards/card_81.png"),
    82: MonsterCard(82, "Ice-Imp", "Uma criatura misteriosa.", Rarity.ULTRA_RARE, Element.FIRE, 8, 2900, 2000, "assets/images/cropped_cards/card_82.png"),
    83: MonsterCard(83, "Ice-Imp (Dup)", "Uma criatura misteriosa.", Rarity.ULTRA_RARE, Element.FIRE, 7, 2700, 2900, "assets/images/cropped_cards/card_83.png"),
    84: MonsterCard(84, "Snow-Snail", "Uma criatura misteriosa.", Rarity.COMMON, Element.FIRE, 3, 1500, 500, "assets/images/cropped_cards/card_84.png"),
    85: MonsterCard(85, "Spoun-Squid", "Uma criatura misteriosa.", Rarity.EPIC, Element.FIRE, 7, 2000, 2200, "assets/images/cropped_cards/card_85.png"),
    86: MonsterCard(86, "Blimmer-Shost", "Uma criatura misteriosa.", Rarity.EPIC, Element.NORMAL, 6, 2000, 1600, "assets/images/cropped_cards/card_86.png"),
    87: MonsterCard(87, "Plimmeg-Snail", "Uma criatura misteriosa.", Rarity.UNCOMMON, Element.NORMAL, 3, 1000, 1100, "assets/images/cropped_cards/card_87.png"),
    88: MonsterCard(88, "Shadow-Snail", "Uma criatura misteriosa.", Rarity.COMMON, Element.FIRE, 3, 700, 500, "assets/images/cropped_cards/card_88.png"),
    89: MonsterCard(89, "Shagon-Shak", "Uma criatura misteriosa.", Rarity.COMMON, Element.NORMAL, 4, 1200, 500, "assets/images/cropped_cards/card_89.png"),
    90: MonsterCard(90, "Pikie-Pup", "Uma criatura misteriosa.", Rarity.EPIC, Element.NORMAL, 6, 2000, 2500, "assets/images/cropped_cards/card_90.png"),
    91: MonsterCard(91, "Star-Sprite", "Uma criatura misteriosa.", Rarity.EPIC, Element.NORMAL, 7, 2100, 1800, "assets/images/cropped_cards/card_91.png"),
    92: MonsterCard(92, "Fre-Froe", "Uma criatura misteriosa.", Rarity.RARE, Element.FIRE, 4, 2000, 2100, "assets/images/cropped_cards/card_92.png"),
    93: MonsterCard(93, "Dragon-Fl7", "Uma criatura misteriosa.", Rarity.UNCOMMON, Element.NORMAL, 5, 1600, 1800, "assets/images/cropped_cards/card_93.png"),
    94: MonsterCard(94, "Steel-Conor", "Uma criatura misteriosa.", Rarity.ULTRA_RARE, Element.NORMAL, 7, 3200, 3000, "assets/images/cropped_cards/card_94.png"),
    95: MonsterCard(95, "Steel-Cohnr", "Uma criatura misteriosa.", Rarity.EPIC, Element.NORMAL, 5, 2800, 2400, "assets/images/cropped_cards/card_95.png"),
    96: MonsterCard(96, "Floht-Shifter", "Uma criatura misteriosa.", Rarity.UNCOMMON, Element.NORMAL, 5, 1300, 1500, "assets/images/cropped_cards/card_96.png"),
}